### ISSUE TITLE
linters configuration from remoet workspace not used

### ISSUE THREAD

**Issue by elf-pavlik** [atom/teletype-client#39] opened 2017-11-17 18:07 UTC
while connecting to remote workspace my atom doesn't use linter configuration in that workspace, it happened at least with `.htmlhintrc` and [linter-htmlhint](https://atom.io/packages/linter-htmlhint)

i can verify if remote configurations work with other linters we use soon

**Comment by jasonrudolph** [comment] 2017-11-17 19:02
Thanks for the report, @elf-pavlik! I am going to close this since it appears to be a duplicate of https://github.com/atom/teletype/issues/228.

Please, subscribe there for updates and add a 👍 emoji reaction to the issue body to let us know that you care about linter support for remote workspaces. We'll be using community feedback to determine where we can deliver the most benefit with the available engineering resources (i.e., full-time Atom engineers, community maintainers, and new contributors).

**Closed by jasonrudolph** 2017-11-17 19:02 UTC
